- packages/oauth/src/__test__/integration.spec.ts
- packages/optimize/src/lib/OptimizeApiClient.ts
- packages/tasklist/src/lib/TasklistApiClient.ts
- packages/zeebe/src/__tests__/integration/Client-setVariables.spec.ts
change constructor to allow passing OAuthProviderImpl
> feat(tasklist): enable multiple clusters via constructor options

- .npmrc
- package-lock.json
- packages/console/package.json
- packages/console/src/lib/ConsoleAPIClient.ts
- packages/modeler/README.md
- packages/modeler/package.json
- packages/modeler/src/lib/ModelerAPIClient.ts
- packages/oauth/package.json
- packages/operate/package.json
- packages/operate/src/__test__/constructor.spec.ts
- packages/operate/src/lib/OperateApiClient.ts
- packages/optimize/package.json
- packages/optimize/src/lib/OptimizeApiClient.ts
- packages/sdk/package.json
- packages/sdk/src/index.ts
- packages/tasklist/package.json
- packages/tasklist/src/__test__/test.spec.ts
- packages/tasklist/src/lib/TasklistApiClient.ts
- packages/zeebe/package.json
- packages/zeebe/src/lib/cancelProcesses.ts
- tsconfig.json
configure packages to publish to @camunda8 org on npm
> refactor(repo): move packages to camunda8 org

- src/__tests__/zeebe/integration/Client-DeleteResource.spec.ts
- src/__tests__/zeebe/integration/Client-ThrowError.spec.ts
- src/__tests__/zeebe/integration/Worker-Failure-Retries.spec.ts
Should fix recent intermittent test failures in CI
> test(zeebe): fix race condition in test

- README.md
- package.json
- src/__tests__/config/jest.cleanup.ts
- src/__tests__/config/jest.globalSetup.ts
- src/__tests__/config/jest.globalTeardown.ts
- src/__tests__/tasklist/tasklist.integration.spec.ts
- src/__tests__/zeebe/integration/Worker-Failure-Retries.spec.ts
- src/__tests__/zeebe/multitenancy/createProcessInstance-mt.spec.ts
- src/admin/lib/AdminApiClient.ts
- src/lib/jest.globalSetup.ts
- src/modeler/lib/ModelerAPIClient.ts
- src/oauth/lib/NullAuthProvider.ts
- src/operate/lib/OperateApiClient.ts
- src/optimize/lib/OptimizeApiClient.ts
- src/tasklist/lib/TasklistApiClient.ts
- src/zeebe/lib/GrpcClient.ts
- src/zeebe/lib/ZBWorkerBase.ts
- src/zeebe/lib/cancelProcesses.ts
- src/zeebe/zb/ZeebeGrpcClient.ts
> feat(repo): add enhanced debug output for http errors

- README.md
- src/__tests__/config/jest.cleanup.ts
- src/__tests__/config/jest.globalSetup.ts
- src/__tests__/config/jest.globalTeardown.ts
- src/__tests__/lib/LosslessJsonParser.spec.ts
- src/__tests__/oauth/OAuthProvider.spec.ts
- src/__tests__/zeebe/integration/Worker-Dto.spec.ts
- src/index.ts
- src/lib/LosslessJsonParser.ts
- src/oauth/lib/OAuthProvider.ts
- src/operate/lib/OperateApiClient.ts
- src/operate/lib/OperateDto.ts
- src/operate/lib/parseSearchResults.ts
- src/tasklist/lib/TasklistApiClient.ts
- src/tasklist/lib/TasklistDto.ts
- src/tasklist/lib/utils.ts
- src/zeebe/lib/ZBWorkerBase.ts
- src/zeebe/lib/interfaces-1.0.ts
- src/zeebe/lib/stringifyVariables.ts
- src/zeebe/zb/ZeebeGrpcClient.ts
> feat(zeebe): implement lossless parsing of job payload

- README.md
> style(formatting): technical review

- .github/workflows/tag-and-publish.yml
> ci(repo): add publish npm package and docs workflow

- .github/workflows/unit.yml
- package.json
- src/__tests__/config/jest.cleanup.ts
> test(repo): skip jest global setup for unit tests

- README.md
> fix(repo): add note on "supported"

- package-lock.json
- package.json
- tsconfig.json
> fix(repo): use ts-patch to transform module mapping in output

- .github/workflows/unit.yml
- README.md
Give a correct example constructor of Camunda8 in the README
fixes #153
> fix(repo): fix example in README

- src/__tests__/config/jest.cleanup.ts
- src/__tests__/testdata/multi-tenant-stream-worker-test.bpmn
- src/__tests__/testdata/multi-tenant-worker-test.bpmn
- src/__tests__/zeebe/multitenancy/multitenant-worker-mt.spec.ts
- src/zeebe/lib/ZBStreamWorker.ts
- src/zeebe/lib/ZBWorkerBase.ts
- src/zeebe/lib/interfaces-1.0.ts
- src/zeebe/zb/ZeebeGrpcClient.ts
adds tenantIds: string[] to stream and polling worker config
fixes #171
> feat(zeebe): add multi-tenant support to workers

- README.md
- src/__tests__/zeebe/integration/Client-DeployResource.spec.ts
- src/zeebe/lib/deployResource.ts
- src/zeebe/zb/ZeebeGrpcClient.ts
add deployResources method
fixes #173
> Deploy-multiple-resources

- README.md
- src/__tests__/zeebe/integration/Client-DeployResource.spec.ts
- src/zeebe/lib/deployResource.ts
- src/zeebe/zb/ZeebeGrpcClient.ts
add deployResources method
fixes #173
> 8.5-deploy-resources

- src/optimize/lib/OptimizeApiClient.ts
it used GET, and it needs to use POST. This is now fixed.
> fix(optimize): fix labelVariables method

- .vscode/settings.json
- src/optimize/lib/OptimizeApiClient.ts
> fix(optimize): fix exportReportDefinitions REST call path

- README.md
Hello team,
First of all thanks for the SDK, it really helped us a lot for our testing the Self-Deployed Camunda 8.
When I was trying and testing the SDK for the first time, I noticed the following difference between the code and the documentation. In the end, I figured it out how to do it. To save others time, I decided to created a PR for this change.
I hope it is helpful for you as well.
Keep up the good work
> fix(docs): update config for disabling authentication

- src/c8/index.ts
The C8 constructor now respects CAMUNDA_OAUTH_STRATEGY
> fix(camunda8): respect CAMUNDA_OAUTH_STRATEGY

- src/zeebe/zb/ZeebeGrpcClient.ts
> feat(zeebe): fix activate jobs stream

- .github/workflows/integration-test.yml
- .github/workflows/pr-test.yml
- .github/workflows/publish.yml
> Docker-compose

- src/lib/Configuration.ts
- src/modeler/lib/ModelerAPIClient.ts
The SaaS Modeler URL is updated.
- [ X ] Bug fix
fixes #203
> fix(modeler): update SaaS URL for Modeler

- src/__tests__/lib/LosslessJsonParser.unit.spec.ts
- src/lib/LosslessJsonParser.ts
> feat(zeebe): support 8.7 string entity keys (backwards-compatible with int64)

- src/__tests__/zeebe/disconnection/disconnect.spec.ts
- src/c8/lib/CamundaRestClient.ts
> fix(camunda8): remove experimental decorator

- README.md
- package-lock.json
- package.json
- src/__tests__/logging/custom-loggers.ts
- src/c8/index.ts
fixes #397
Read the robot's review below.
> fix: add tests and documentation for logging

- src/__tests__/8.7-sm-only/deleteDocument.spec.ts
- src/c8/lib/CamundaRestClient.ts
Implement deleteDocument. closes Implement Delete document #299
> feat(camunda8): implement deleteDocument. 

- src/__tests__/8.7-sm-only/uploadDocuments.spec.ts
- src/c8/lib/C8Dto.ts
- src/c8/lib/CamundaRestClient.ts
Implement upload multiple documents
> feat(camunda8): implement uploadDocuments. closes Implement Upload multiple documents #404

- src/__tests__/c8/rest/modifyProcessInstance.rest.spec.ts
- src/__tests__/testdata/modify-process-instance-rest.bpmn
- src/c8/lib/C8Dto.ts
- src/c8/lib/CamundaRestClient.ts
Implement modifyProcessInstance
> feat(camunda8): implement modifyProcessInstance. closes Implement Modify process instance #321

- src/__tests__/c8/rest/evaluateDecision.rest.spec.ts
- src/__tests__/testdata/test-drd.dmn
- src/c8/lib/C8Dto.ts
- src/c8/lib/CamundaRestClient.ts
> Evaluate-decision

- .github/workflows/pr-test.yml
- src/__tests__/8.7-sm-only/callAlphaApiEndpoint.rest.spec.ts
- src/__tests__/8.7-sm-only/uploadDocuments.spec.ts
- src/__tests__/8.7-sm-only/userTasks.rest.spec.ts
- src/__tests__/c8/rest/callApiEndpoint.rest.spec.ts
- src/c8/index.ts
- src/c8/lib/C8Dto.ts
- src/c8/lib/CamundaRestClient.ts
Add generic `callApiEndpoint` method. Closes #423.
> Fix 423 - add callApiEndpoint method. Closes #423

- README.md
Add link to complete configuration in README
> docs: add link to complete configuration in README. fixes #454

- README.md
- package-lock.json
- src/index.ts
- src/lib/CamundaSupportLogger.ts
- src/lib/Configuration.ts
- src/lib/GotHooks.ts
- src/zeebe/lib/GrpcClient.ts
- src/zeebe/zb/ZBWorker.ts
Add `CAMUNDA_SUPPORT_LOG_ENABLED` env var and debug and trace log file output.
> feat: debug and trace support log infrastructure. fixes #457

- package-lock.json
- package.json
- src/zeebe/lib/StatefulLogInterceptor.ts
- src/zeebe/lib/ZBLogger.ts
- src/zeebe/lib/interfaces-1.0.ts
> feat: enhance context output for ZeebeGrpcClient log messages. fixes #467

- src/zeebe/lib/ZBWorkerBase.ts
> fix: do not remove stream listeners on stream end. fixes #466

- src/__tests__/8.8/getVariable.spec.ts
- src/__tests__/testdata/rest-get-variable.bpmn
- src/c8/lib/C8Dto.ts
- src/c8/lib/CamundaRestClient.ts
> feat: add getVariable to Rest API client. Fixes #344

- src/zeebe/lib/GrpcClient.ts
- src/zeebe/lib/ZBStreamWorker.ts
- src/zeebe/lib/ZBWorkerBase.ts
- src/zeebe/zb/ZeebeGrpcClient.ts
Destroy streams rather than removing listeners.
> fix: destroy streams rather than removing all listeners. Fixes #466

- src/__tests__/8.8/getProcessDefinitionXML.spec.ts
- src/c8/lib/CamundaRestClient.ts
Implement Process Definition XML.
> feat: implement getProcessDefinitionXML. fixes #317

- src/__tests__/8.8/searchElementInstances.spec.ts
- src/__tests__/testdata/rest-search-element-instances-test.bpmn
- src/c8/lib/C8Dto.ts
- src/c8/lib/CamundaRestClient.ts
Implement searchElementInstances.
> feat: implement searchElementInstances. fixes #301

- src/__tests__/c8/rest/updateElementInstanceVariables.spec.ts
- src/c8/lib/CamundaRestClient.ts
- src/index.ts
Fixes the implementation of updateElementInstanceVariables and adds a test for it.
> fix: fix implementation of updateElementInstanceVariables. fixes #495

- src/__tests__/8.8/searchIncidents.spec.ts
- src/__tests__/testdata/searchIncidentsTest.bpmn
- src/c8/lib/C8Dto.ts
- src/c8/lib/CamundaRestClient.ts
> feat: implement searchIncidents. fixes  #310

- src/c8/lib/CamundaRestClient.ts
- src/lib/GotHooks.ts
- src/oauth/lib/OAuthProvider.ts
> feat: correctly handle backpressure 503 response. fixes #509

- src/c8/lib/C8Dto.ts
- src/c8/lib/C8DtoInternal.ts
- src/c8/lib/CamundaRestClient.ts
> fix: export SearchUsersRequest type
