camunda/camunda-8-js-sdk

package-lock.json
packages/tasklist-client-node-js/.env.example
packages/tasklist-client-node-js/DEVELOP.md
packages/tasklist-client-node-js/package.json
packages/tasklist-client-node-js/src/__test__/restclient.spec.ts
packages/tasklist-client-node-js/src/__test__/test.spec.ts

Adds the `dotenv` dependency, and configures the Tasklist specs to import environment variables from a `.env` file. Also includes a `.env.example` file including all the necessary keys, and docs on how to set up a valid `.env` file.
I only applied this to the Tasklist client, but maybe it's something we want to apply to all of them.

feat: pull tasklist environment configuration from .env file in specs

---

packages/tasklist-client-node-js/src/__test__/restclient.spec.ts
packages/tasklist-client-node-js/src/__test__/test.spec.ts
packages/tasklist-client-node-js/src/lib/TasklistRESTClient.ts
packages/tasklist-client-node-js/src/lib/Types.ts

~BLOCKED by #6 and #7. This PR targets the branch from #7, to avoid noise in the diff. Once 6 & 7 are merged, this should auto-adjust to targeting `main`.~
---
At least partially addresses https://github.com/camunda-community-hub/tasklist-client-node-js/issues/14.
* Gets existing Tasklist REST specs passing (or removes them in a couple cases).
* Updates the Tasklist types to accommodate a change that allows the REST specs to pass (described in-line).
There is [an important question in the in-line comments](https://github.com/camunda-community-hub/camunda-8-js-sdk/pull/8#discussion_r1421087530) about a decision I made. 
* I initially thought I could refactor the tests to only spin up a process instance once per test suite, instead of once per test...but I ran into issues with this in the …

feat: get Tasklist REST API and specs working/passing

---

.github/workflows/commitlint.yml
.vscode/settings.json
package-lock.json
packages/oauth/package.json
packages/oauth/src/__test__/OAuthImpl.spec.ts
packages/oauth/src/lib/OAuthProviderImpl.ts

Replace node-specific got with isomorphic fetch.

refactor(oauth): replace got with isomorphic-fetch

---

.github/workflows/commitlint.yml
src/__tests__/testdata/MigrateProcess-Version-1.bpmn
src/__tests__/testdata/MigrateProcess-Version-2.bpmn
src/__tests__/zeebe/integration/Client-MigrateProcessInstance.spec.ts
src/zeebe/lib/interfaces-1.0.ts
src/zeebe/lib/interfaces-grpc-1.0.ts
src/zeebe/zb/ZeebeGrpcClient.ts

feat(zeebe): add MigrateProcessInstance

---

.github/workflows/code-scanning.yml
README.md

ci(repo): add CodeQL scanning

---

src/tasklist/lib/TasklistApiClient.ts

Hello,
I am getting 500 error without specifying optional `includeVariables`, so I have to workaround it like so:
```js
const taskVariables = await tasklist.getVariables({
taskId,
includeVariables: []
});
```
But anyway, here's the fix for that problem.

Fix default value of includeVariables parameter in tasklist api client

---

src/zeebe/lib/GrpcClient.ts

"waitForReady" was called with a deadline of 10000 milliseconds.
But the method 'watchConnectivityState' used by 'waitForReady', needs a deadline date. 
cf: [https://github.com/grpc/grpc-node/blob/%40grpc/grpc-js%401.9.7/packages/grpc-js/src/internal-channel.ts#L739](https://github.com/grpc/grpc-node/blob/%40grpc/grpc-js%401.9.7/packages/grpc-js/src/internal-channel.ts#L739)
This caused to throw error "Deadline passed without connectivity state change" in "watchConnectivityState" every time.
So this fix is to set the deadline date at now + 10s

Fix: The deadline passed to 'waitForReady' in "GrpcClient", was a millisecond gap, but the method needs a date or a TS of the deadline

---

src/zeebe/lib/GrpcClient.ts

Reverts camunda/camunda-8-js-sdk#148

Revert "Fix: The deadline passed to 'waitForReady' in "GrpcClient", was a millisecond gap, but the method needs a date or a TS of the deadline"

---

src/__tests__/zeebe/integration/Client-ConnectionError.spec.ts
src/__tests__/zeebe/integration/Client-onReady.spec.ts
src/__tests__/zeebe/integration/Worker-onReady.spec.ts
src/zeebe/lib/GrpcClient.ts

This fixes a bug in the grpc channel connection sensing
fixes #150

fix(zeebe): fix waitForReady deadline

---

.gitignore
src/__tests__/lib/GetCustomCertificateBuffer.unit.spec.ts
src/__tests__/zeebe/integration/Client-ConnectionError.spec.ts
src/__tests__/zeebe/integration/Client-ThrowError.spec.ts
src/__tests__/zeebe/integration/Client-onReady.spec.ts
src/__tests__/zeebe/integration/Worker-onReady.spec.ts
src/generated/zeebe_grpc_pb.ts
src/generated/zeebe_pb.d.ts
src/lib/Configuration.ts
src/lib/GetCustomCertificateBuffer.ts
src/zeebe/lib/ConnectionFactory.ts
src/zeebe/lib/GrpcClient.ts
src/zeebe/lib/GrpcMiddleware.ts
src/zeebe/zb/ZeebeGrpcClient.ts

accept a custom certificate as a string argument to the configuration
fixes #142

feat(repo): add CAMUNDA_CUSTOM_ROOT_CERT_STRING parameter

---

.github/workflows/unit.yml
README.md

Give a correct example constructor of Camunda8 in the README
fixes #153

fix(repo): fix example in README (#154)

---

src/oauth/lib/OAuthProvider.ts

Hi team,
first of all a big thanks for this sdk! We plan to use it at Mercedes-Benz to connect zeebe workers to our self-managed camunda instance.
In our setup, were we have to put both the oAuth server (keycloak) and the zeebe gateway behind an ingress which requires **mTLS client authorization**. As I've tested, client authorization has already been supported for grpc connections, but the OAuthProvider did not support it yet when it requests a token.
So I've added code that uses the same config parameters `CAMUNDA_CUSTOM_CERT_CHAIN_PATH` and `CAMUNDA_CUSTOM_PRIVATE_KEY_PATH` to configure got, but only in case they're set. If they're not set, `key`and `cert`params from got remain `undefined`, and everything works normal.

Add support for oAuth mTLS client authorization

---

src/__tests__/testdata/Client-Update-Job-Timeout.bpmn
src/__tests__/zeebe/integration/Client-Update-Job-Timeout.spec.ts
src/zeebe/lib/interfaces-1.0.ts
src/zeebe/lib/interfaces-grpc-1.0.ts
src/zeebe/zb/ZeebeGrpcClient.ts

feat(zeebe): add updateJobTimeout method

---

src/__tests__/config/jest.cleanup.ts
src/__tests__/testdata/multi-tenant-stream-worker-test.bpmn
src/__tests__/testdata/multi-tenant-worker-test.bpmn
src/__tests__/zeebe/multitenancy/multitenant-worker-mt.spec.ts
src/zeebe/lib/ZBStreamWorker.ts
src/zeebe/lib/ZBWorkerBase.ts
src/zeebe/lib/interfaces-1.0.ts
src/zeebe/zb/ZeebeGrpcClient.ts

adds tenantIds: string[] to stream and polling worker config
fixes #171

feat(zeebe): add multi-tenant support to workers

---

src/optimize/lib/OptimizeApiClient.ts

Originally reported by @SamanthaHolstine in Camunda internal Slack.
This PR corrects the audience argument for getting an auth token from the OptimizeApiClient. 
The OptimizeApiClient was passing the `OPERATE` audience, instead of `OPTIMIZE`. This was resulting in any request to an authorized Optimize endpoint failing, with a `401 Unauthorized` response.
I confirmed with a local reproduction that changing to `OPTIMIZE` fixes the issue. I didn't find an existing place to put a test; let me know if I overlooked something, or if you have suggestions on how I can include a test for this behavior.
Note also that I made this commit with the `--no-verify` flag, because I could not get unit tests passing locally, seemingly unrelated to my change. See below for the tests that consistently failed …

fix: specify the correct audience when getting an Optimize auth token

---

src/__tests__/testdata/message-correlation-test.bpmn
src/__tests__/zeebe/integration/Client-PublishMessage.spec.ts

add test for message correlation

test(zeebe): add message correlation test

---

src/admin/lib/AdminApiClient.ts

removed 'clusters' from prefixUrl and updated clusters endpoint urls to include 'clusters/...'

fix(admin): fix members endpoint - fixes #206

---

src/__tests__/config/jest.cleanup.ts
src/lib/Configuration.ts
src/zeebe/zb/ZeebeGrpcClient.ts

add support for ZEEBE_INSECURE_CONNECTION env var to disable TLS on the Zeebe gRPC connection

feat(zeebe): add support for ZEEBE_INSECURE_CONNECTION env var

---

.vscode/settings.json
src/__tests__/lib/LosslessJsonParser.unit.spec.ts
src/lib/LosslessJsonParser.ts

the lossless parser now correctly handles null fields in objects
fixes #212

fix(lossless-parser): correctly handle null in objects

---

src/oauth/lib/OAuthProvider.ts

clientId and clientSecret containing special characters are correctly handled
fixes #230

fix(oauth): uri encode clientId and clientSecret

---

src/zeebe/lib/ZBStreamWorker.ts
src/zeebe/lib/ZBWorkerBase.ts
src/zeebe/lib/stringifyVariables.ts
src/zeebe/zb/ZeebeGrpcClient.ts

if the variable payload cannot be parsed, fail the job rather than throwing an error
fixes #236
[Describe your changes here]

fix(zeebe): fail job if variables cannot be parsed

---

src/operate/lib/OperateApiClient.ts
src/operate/lib/OperateDto.ts

closes #262 
DecisionInstance type should also include processInstanceKey, which is also addressed in this PR
[Describe your changes here]

fix(operate): use post request for decision definitions and decision instances endpoints

---

src/__tests__/modeler/modeler-integration.spec.ts
src/modeler/lib/ModelerAPIClient.ts
src/modeler/lib/ModelerDto.ts

Fixes the search and upload methods for files.
- [ X ] Bug fix

fix(modeler): correct HTTP methods for file methods. fixes #269

---

README.md
package-lock.json
package.json
src/__tests__/modeler/modeler-integration.spec.ts
src/__tests__/zeebe/integration-rest/UserTask-rest.spec.ts
src/__tests__/zeebe/integration/Client-Update-Job-Timeout.spec.ts
src/__tests__/zeebe/integration/Worker-Failure-Retries.spec.ts
src/__tests__/zeebe/integration/Worker-Failure.spec.ts
src/lib/Configuration.ts
src/zeebe/lib/GrpcClient.ts
src/zeebe/lib/ZBWorkerBase.ts
src/zeebe/lib/interfaces-1.0.ts

* Update to latest version of `@grpc/grpc-js` dependency, fixes misleading GRPC ERROR 8 on gateway timeout.
* Release stream resources on stream end.
* Change worker longpoll default to 50s (to avoid 504 Timeout on SaaS at 60s).
Fixes #229 
Fixes #281

fix(zeebe): update JS GPRC lib dependency, release stream resources on end

---

README.md
src/zeebe/lib/ZBWorkerBase.ts

Change the level of the "polling blocked" message in the Zeebe Worker to verbose (was debug). 

fix(zeebe): move polling blocked log message to new verbose level. fixes #356

---

.vscode/launch.json
README.md
src/__tests__/zeebe/integration/Worker-Backoff.spec.ts
src/lib/Configuration.ts
src/zeebe/lib/ConnectionStatusEvent.ts
src/zeebe/lib/GrpcClient.ts
src/zeebe/lib/TypedEmitter.ts
src/zeebe/lib/ZBWorkerBase.ts
src/zeebe/lib/interfaces-1.0.ts
src/zeebe/zb/ZeebeGrpcClient.ts

fixes #366
- Backoff on UNAUTHENTICATED error.
- Implement custom backoff time configuration.

feat(zeebe): implement backoff on UNAUTHENTICATED error for workers

---

src/__tests__/oauth/OAuthProvider.unit.spec.ts
src/admin/lib/AdminApiClient.ts
src/c8/lib/CamundaRestClient.ts
src/modeler/lib/ModelerAPIClient.ts
src/oauth/lib/BasicAuthProvider.ts
src/oauth/lib/BearerAuthProvider.ts
src/oauth/lib/OAuthProvider.ts
src/operate/lib/OperateApiClient.ts
src/optimize/lib/OptimizeApiClient.ts
src/tasklist/lib/TasklistApiClient.ts
src/zeebe/lib/GrpcClient.ts
src/zeebe/zb/ZeebeRESTClient.ts

fixes #367
Passes out the entire authorization header from the `getToken` method. This allows the correct Basic Auth header to be used.

fix(oauth): pass out full auth header from getToken method

---

src/__tests__/operate/operate-integration.spec.ts
src/operate/lib/OperateApiClient.ts

fixes #387
This pull request fixes issue https://github.com/camunda/camunda-8-js-sdk/issues/387 by enabling paging for fetching variables of a process instance via the Operate API client. Key changes include:
Replacing a fixed timeout with a polling loop to wait for a process instance.
Adding a new test to validate the paging mechanism in getVariablesforProcess.
Updating the OperateApiClient to support pagination options.

fix(operate): allow paging for getVariablesforProcess

---

src/c8/lib/CamundaJobWorker.ts

Fix a bug when currentlyActiveJobsCount = maxJobsToActivate, the client stops polling for new jobs.
Restart job polling if currentlyActiveJobsCount = maxJobsToActivate

fix: polling when maxJobsToActivate is reached

---

src/__tests__/8.7-sm-only/userTasks.rest.spec.ts
src/c8/lib/C8Dto.ts
src/c8/lib/CamundaRestClient.ts

Rename Dtos for search methods over the REST API.
This will be a breaking change for anyone using the Dtos for the search methods - which should be no-one right now, because this is in alpha in 8.6/8.7.

fix(camunda8): standardise on search for methods. closes #363

---

package-lock.json
package.json
src/__tests__/c8/rest/activateJobs.rest.spec.ts
src/__tests__/c8/rest/jobWorker.rest.spec.ts
src/c8/lib/C8Dto.ts
src/c8/lib/CamundaJobWorker.ts
src/c8/lib/CamundaRestClient.ts
src/lib/Configuration.ts

This PR makes activeJobs REST calls cancelable by updating the REST client to return PCancelable promises and integrating cancellation handling into the job worker.
Updated configuration adds an option ('none') to suppress logging.
Modified CamundaRestClient methods (activateJobs and callApiEndpoint) to support cancellation using PCancelable, and refactored related types.
Enhanced job worker cancellation logic and added tests to verify cancellation behavior.

feat: make activeJobs REST calls cancelable. fixes #424

---

README.md
src/lib/Configuration.ts

This pull request updates the documentation and comments related to TLS and mTLS configuration.
Updated comments in Configuration.ts to clarify the usage of certificates and keys for both TLS and mTLS.
Added a new TLS/mTLS section in the README to guide users on configuring these settings.

fix: update documentation around TLS and mTLS configuration, fixes #395

---

src/c8/lib/C8Dto.ts

This PR renames the property in the PublishMessageResponse DTO to align with the API.
Renamed the property from "key" to "messageKey".

fix: rename messageKey in PublishMessageResponse Dto

---

README.md
src/__tests__/c8/rest/refreshBearerToken.unit.spec.ts
src/c8/lib/CamundaRestClient.ts
src/oauth/lib/BearerAuthProvider.ts

This PR implements a new feature to allow dynamic updates of the Bearer token used for OAuth authentication. The key changes include:
* Converting the `bearerToke` property in BearerAuthProvider from private to protected.
* Adding a public `setToken` method on BearerAuthProvider.
* Introducing a new `setBearerToken` method in CamundaRestClient with accompanying tests and updated documentation in the README.

feat: allow dynamic update of Bearer token. fixes #445

---

README.md
src/__tests__/c8/rest/refreshBearerToken.unit.spec.ts
src/c8/index.ts
src/c8/lib/CamundaRestClient.ts
src/oauth/index.ts
src/oauth/lib/BearerAuthProvider.ts
src/oauth/lib/IOAuthProvider.ts
src/zeebe/lib/GrpcClient.ts

This pull request enables arbitrary headers on requests by modifying the OAuth token handling in the GrpcClient and updating related provider interfaces and tests.
Refactored token handling in GrpcClient to support multiple headers
Updated IOAuthProvider and BearerAuthProvider to be more generic
Modified documentation and tests to reflect the new behavior
This also reverts the addition of the `setBearerToken` method on the CamundaRestClient, for the more generic and correctly encapsulated injection of an IOAuthProvider.

feat: enable arbitrary headers on requests. fixes #448

---

.gitignore
src/admin/lib/AdminApiClient.ts
src/c8/lib/CamundaRestClient.ts
src/lib/GotHooks.ts
src/modeler/lib/ModelerAPIClient.ts
src/oauth/lib/CookieAuthProvider.ts
src/oauth/lib/OAuthProvider.ts
src/operate/lib/OperateApiClient.ts
src/optimize/lib/OptimizeApiClient.ts
src/tasklist/lib/TasklistApiClient.ts
src/zeebe/zb/ZeebeRESTClient.ts

This PR adds hinting for REST errors by updating error handling hooks across multiple API client modules.
Replaces gotErrorHandler with beforeCallHook to capture call context.
Updates beforeError hooks to pass the configuration object to gotBeforeErrorHook for enriched error messages.

feat: add hinting for Rest errors. fixes #456

---

package-lock.json
package.json
src/lib/Configuration.ts

Thanks for using `neon-env`! I'm a maintainer of the package, and today `neon-env` [was moved over](https://github.com/SuperchupuDev/neon-env/releases/tag/0.2.3) to `typed-env`, and the former was deprecated. `neon-env` started out being a maintained fork of `typed-env`, and now the maintainers of both packages agreed to merge it into `typed-env` and resume any further development there.
(None? (refactor))
In theory there are no further code changes needed, as `typed-env@2.0.0` shares the same code as the latest version of `neon-env`. Although `@camunda8/sdk` uses an old version of `neon-env`, it should be fine as there are no significant breaking changes affecting the upgrade here

refactor: replace `neon-env` with `typed-env`

---

src/zeebe/zb/ZeebeGrpcClient.ts

check the existing correlationKey first instead of using uuid() every time
-  Bug fix

Fix: Check for an Existing correlationKey Before Generating a New UUID

---

src/lib/Configuration.ts
src/zeebe/lib/ZBLogger.ts

Prevent ZBLogger crash when stacktrace is undefined

fix: prevent ZBLogger crash when stacktrace is undefined

---

src/__tests__/zeebe/integration-rest/UserTask-rest.spec.ts
src/lib/GotHooks.ts

Implement backoff retry on HTTP status code 429 "Too many requests" for the Rest APIs.

feat: backoff retry on 429 "Too many client requests". FIxes #528

---

.github/workflows/integration-test.yml
.github/workflows/pr-test.yml
env/c8run.env
src/__tests__/8.7-sm-only/deleteDocument.spec.ts
src/__tests__/8.7-sm-only/uploadDocument.spec.ts
src/__tests__/8.7-sm-only/uploadDocuments.spec.ts
src/__tests__/lib/ZeebeGrpcAddress.unit.spec.ts
src/lib/GotHooks.ts

Signed-off-by: Josh Wulf <josh.wulf@camunda.com>
- Disables Document API tests. 
Should be revisited with the 8.8.0-alpha7 release to see if it is still necessary.

ci: disable flaky tests

---

README.md

Use the right names for configuration variables for COOKIE auth in README. cf. implementation in https://github.com/camunda/camunda-8-js-sdk/blob/main/src/oauth/lib/CookieAuthProvider.ts#L41. This seems to be the only place where it is wrong, but in the forum its also wrong: https://forum.camunda.io/t/js-sdk-authentication-for-c8run/61295

fix(docs): adjust variable names for cookie auth

---

src/c8/index.ts
src/zeebe/lib/stringifyVariables.ts

Adds cache control to Camunda8 to allow creation of new clients.

feat: add ability to override caching of clients. fixes #575
